version: "3.4"
services:
  java:
    build: .
    ports:
    - "8089:8080"
    environment:
    - SPRING_PROFILES_ACTIVE=local
    - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/challenge
    profiles: ["java"]
  postgres:
    image: postgres:13.1
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=challenge
      - POSTGRES_DB=challenge
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
    - "15672:15672"
    - "5672:5672"
    environment:
    - RABBITMQ_DEFAULT_USER=rabbit
    - RABBITMQ_DEFAULT_PASS=carrot

